### ISSUE TITLE
Requests version in requirements.txt is too old, change to >= 2.3.0

### ISSUE THREAD

**Issue by migurski** [Lukasa/requests-ftp#12]
Requests 1.0.0+ is [listed in `requirements.txt`](https://github.com/Lukasa/requests-ftp/blob/83b7dc59ec6b4e459d8e22a9999bc1ec37c173cf/requirements.txt), but Requests FTP relies on `ConnectTimeout` which only appeared [as of `c2aeaa3`](https://github.com/kennethreitz/requests/commit/c2aeaa3959b5754f5b39a45bceff91b196b6c986), probably Requests version 2.3.0:

```
  File "/usr/local/lib/python2.7/dist-packages/requests_ftp/__init__.py", line 21, in <module>
    from .ftp import FTPAdapter, monkeypatch_session
  File "/usr/local/lib/python2.7/dist-packages/requests_ftp/ftp.py", line 13, in <module>
    from requests.exceptions import ConnectionError, ConnectTimeout, ReadTimeout
ImportError: cannot import name ConnectTimeout
```

**Comment by yarikoptic** [comment]
Since still open I guess this module is not maintained

**Comment by emanuil-tolev** [comment]
It is looking for a maintainer I think.  I'm using it in production and trying to find enough time to get into its guts properly, but have only managed short bursts  of activity so far.  I'll still try to help if you have a problem. 

You can submit a PR for this particular issue easily. In fact I might look at doing that over the weekend as well.

**Comment by Lukasa** [comment]
That's correct. I am willing to review and merge fixes, but this module is outside my professional remit so I really have no time to actively develop it.

**Comment by yarikoptic** [comment]
I am away from the keyboard ATM so submitted the PR on the phone to close this one based on original report information.
