### ISSUE TITLE
Enable continuous integration with Travis

### ISSUE THREAD

**Issue by femtotrader** [Lukasa/requests-ftp#16]
Hello,

it will be nice if Continuous Integration (with Travis for example) could be enabled.

Kind regards

**Comment by Lukasa** [comment]
This is done.

**Comment by femtotrader** [comment]
Thanks

Maybe you should add a badge to `README.rst` like [![Build Status](https://travis-ci.org/Lukasa/requests-ftp.svg?branch=master)](https://travis-ci.org/Lukasa/requests-ftp)

using

```
.. image:: https://travis-ci.org/Lukasa/requests-ftp.svg?branch=master
    :target: https://travis-ci.org/Lukasa/requests-ftp
```
