### ISSUE TITLE
requests-ftp maintenance

### ISSUE THREAD

**Issue by emanuil-tolev** [Lukasa/requests-ftp#18]
hey @Lukasa 

You say in https://github.com/Lukasa/requests-ftp/issues/10#issuecomment-165508624

> @adrienbrunet This library is definitely far from perfection: it was mostly intended as a joke when I originally wrote it! I'm definitely open to finding someone else to take over maintenance of it and to turn it into something more useful, so if you feel like proposing some pull requests and getting this library up and running into something better, I'll happily consider taking on a maintainer.

What does that mean in immediate practical terms? Do you think it should be rewritten to be more .. in line with whatever best practices there are for requests transport adapters? And some tests.

I think it's a very useful obvious hole for those just looking to interact with FTP in ~2 lines. I'm not offering to be a maintainer since for me that just means trying to do what's needed and make lots of PRs, and if I can make the time for that then presto.

**Comment by Lukasa** [comment]
In practical terms it means that this library attracts the bare minimum of my time. It means I do my best to review and merge pull requests when they're provided, and may attempt bug fixes, but that it's just not the focus of my work: I have too many other things to be doing.

In general, if someone finds this useful enough that they'd like it to be "production ready", I'm happy to work with that person to make it possible for them to do so, and in doing so hand control of the library to them. However, if no such person is willing to stand up, then the library will continue more or less in the same way as before.

**Comment by emanuil-tolev** [comment]
> In practical terms it means that this library attracts the bare minimum of my time. It means I do my best to review and merge pull requests when they're provided, and may attempt bug fixes, but that it's just not the focus of my work: I have too many other things to be doing.

Sorry, of course - by "immediate practical terms" I meant what did you think was the best direction for the library to take. But it's probably best to just talk about that with the person who does make time for the lib. I'm trying to make time this week and early Jan. If I can resolve most of the issues listed I'll have proven to myself I do have the time, and built up a sufficient understanding of the library.

Nothing more to add to this specific issue though, I'll see if I succeed in the above.
