### ISSUE TITLE
PyPI link to repo wrong

### ISSUE THREAD

**Issue by emanuil-tolev** [Lukasa/requests-ftp#8]
https://pypi.python.org/pypi/requests-ftp/0.2.0

has

http://github.com/Lukasa/requests_ftp

in the metadata ("Homepage" part). s/_/-/ :).

Also may be good to include a correct link under Contribute section.

EDIT: Er, you have fixed it in setup.py. Maybe it needs a new release in order to update it. Feel free to close if so.

**Comment by QuLogic** [comment]
This appears corrected now?

**Comment by emanuil-tolev** [comment]
Indeed, thanks.
